version: "2"
services:
  proxy:
      image: diogok/caddy
      restart: "always"
      ports:
        - 80:80
        - 443:443
      networks:
        - nuvem
      volumes:
        - ./Caddyfile:/etc/Caddyfile
        - /opt/caddy:/root/.caddy
  elasticsearch:
      image: cncflora/elasticsearch
      container_name: elasticsearch
      networks:
        - nuvem
      restart: "always"
      ports:
          - "9200:9200"
      volumes:
          - "/var/data/elasticsearch/data:/usr/share/elasticsearch/data:rw"
  kibana:
      image: cncflora/kibana
      container_name: kibana
      networks:
        - nuvem
      restart: "always"
      ports:
          - "80"
  couchdb:
      image: cncflora/couchdb
      container_name: couchdb
      networks:
        - nuvem
      restart: "always"
      ports:
          - "5984:5984"
      volumes:
          - "/var/data/couchdb:/var/lib/couchdb:rw"
  floradata:
      image: cncflora/floradata
      container_name: floradata
      networks:
        - nuvem
      restart: "always"
      ports:
          - 80
          - 9001
  aka:
      image: cncflora/aka
      container_name: aka
      networks:
        - nuvem
      restart: "always"
      ports:
          - 8080
      volumes:
          - "/var/data/aka:/var/data/aka:rw"
      environment:
          PROXY: "/aka"
  services:
      image: cncflora/services
      container_name: services
      networks:
        - nuvem
      restart: "always"
      ports:
          - "80"
      environment:
          DB: "public"
          BASE: "/services"
  portal:
      image: cncflora/portal
      container_name: portal
      networks:
        - nuvem
      restart: "always"
      environment:
          BASE: "/portal"
      ports:
          - 80
  entrypoint: 
      image: cncflora/entrypoint
      container_name: entrypoint
      networks:
        - nuvem
      restart: "always"
      ports:
          - "80"
  connect:
      image: cncflora/connect
      container_name: connect
      networks:
        - nuvem
      restart: "always"
      ports:
          - "80"
      volumes:
          - "/var/data/connect:/var/floraconnect:rw"
      environment:
          PROXY: "/connect"
  dwc_services:
      image: cncflora/dwc-services
      container_name: dwc_services
      networks:
        - nuvem
      restart: "always"
      ports:
          - "80"
      environment:
          PROXY: "/dwc_services"
  checklist:
      image: cncflora/checklist
      container_name: checklist
      networks:
        - nuvem
      restart: "always"
      ports:
          - "80"
      environment:
          BASE: "/checklist"
          HOST: "${HOST}"
  occurrences:
      image: cncflora/occurrences
      container_name: occurrences
      networks:
        - nuvem
      restart: "always"
      ports:
          - "80"
      environment:
          BASE: "/occurrences"
          HOST: "${HOST}"
  profiles:
      image: cncflora/profiles
      container_name: profiles
      networks:
        - nuvem
      restart: "always"
      ports:
          - "80"
      environment:
          BASE: "/profiles"
          HOST: "${HOST}"
  assessments:
      image: cncflora/assessments
      container_name: assessments
      networks:
        - nuvem
      restart: "always"
      ports:
          - "80"
      environment:
          BASE: "/assessment"
          HOST: "${HOST}"
  migrator:
      image: cncflora/migrator
      container_name: migrator
      networks:
        - nuvem
      restart: "always"
      ports:
          - "80"
      environment:
          HOST: "${HOST}"
  reports2:
      image: cncflora/reports2
      container_name: reports2
      networks:
        - nuvem
      restart: "always"
      ports:
          - "80"
  arquivos:
      image: cncflora/apache
      container_name: arquivos
      networks:
        - nuvem
      restart: "always"
      ports:
          - "80"
      volumes:
          - "/var/data/www:/var/www:rw"
  arquivos-sftp:
      image: asavartzeth/sftp
      container_name: arquivos-sftp
      networks:
        - nuvem
      restart: "always"
      ports:
          - "2223:22"
      environment:
          SFTP_USER: "cncflora"
          SFTP_PASS: "1cncflora2"
      volumes:
          - "/var/data/www:$SFTP_DATA_DIR/chroot/www:rw"
  plataforma2:
      image: cncflora/apache
      container_name: plataforma2
      networks:
        - nuvem
      restart: "always"
      ports:
          - "80"
      volumes:
        - "/var/data/www-old:/var/www:rw"
networks:
  nuvem:
