proxy:
    image: cncflora/proxy
    container_name: proxy
    restart: "always"
    environment:
        ROOT_APP: "portal"
    ports:
        - "80:80"
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
elasticsearch:
    image: cncflora/elasticsearch
    container_name: elasticsearch
    restart: "always"
    ports:
        - "9200:9200"
    volumes:
        - "/var/data/elasticsearch/data:/usr/share/elasticsearch/data:rw"
kibana:
    image: cncflora/kibana
    container_name: kibana
    restart: "always"
    ports:
        - "80"
    links:
        - "elasticsearch:elasticsearch"
download_csv:
    image: cncflora/download_csv
    container_name: download_csv
    restart: "always"
    ports:
        - "80"
    environment:
        HOST: "${HOST}"
couchdb:
    image: cncflora/couchdb
    container_name: couchdb
    restart: "always"
    ports:
        - "5984:5984"
        - "9001"
    volumes:
        - "/var/data/couchdb:/var/lib/couchdb:rw"
    links:
        - "elasticsearch:elasticsearch"
floradata:
    image: cncflora/floradata
    container_name: floradata
    restart: "always"
    ports:
        - 80
        - 9001
aka:
    image: cncflora/aka
    container_name: aka
    restart: "always"
    ports:
        - 8080
    volumes:
        - "/var/data/aka:/var/data/aka:rw"
    environment:
        PROXY: "/aka"
services:
    image: cncflora/services
    container_name: services
    restart: "always"
    links:
        - "floradata:floradata"
        - "couchdb:couchdb"
        - "elasticsearch:elasticsearch"
        - "aka:aka"
    ports:
        - "80"
    environment:
        DB: "public"
        BASE: "/services"
portal:
    image: cncflora/portal
    container_name: portal
    restart: "always"
    environment:
        BASE: "/portal"
    ports:
        - 80
entrypoint: 
    image: cncflora/entrypoint
    container_name: entrypoint
    restart: "always"
    ports:
        - "80"
connect:
    image: cncflora/connect
    container_name: connect
    restart: "always"
    ports:
        - "80"
    volumes:
        - "/var/data/connect:/var/floraconnect:rw"
    environment:
        PROXY: "/connect"
dwc_services:
    image: cncflora/dwc-services
    container_name: dwc_services
    restart: "always"
    ports:
        - "80"
    environment:
        PROXY: "/dwc_services"
checklist:
    image: cncflora/checklist
    container_name: checklist
    restart: "always"
    ports:
        - "80"
    environment:
        BASE: "/checklist"
        HOST: "${HOST}"
    links:
        - elasticsearch:elasticsearch
        - couchdb:couchdb
        - connect:connect
        - floradata:floradata
occurrences:
    image: cncflora/occurrences
    container_name: occurrences
    restart: "always"
    ports:
        - "80"
    environment:
        BASE: "/occurrences"
        HOST: "${HOST}"
    links:
        - elasticsearch:elasticsearch
        - couchdb:couchdb
        - connect:connect
        - dwc_services:dwc_services
profiles:
    image: cncflora/profiles
    container_name: profiles
    restart: "always"
    ports:
        - "80"
    environment:
        BASE: "/profiles"
        HOST: "${HOST}"
    links:
        - elasticsearch:elasticsearch
        - couchdb:couchdb
        - connect:connect
        - floradata:floradata 
assessments:
    image: cncflora/assessments
    container_name: assessments
    restart: "always"
    ports:
        - "80"
    environment:
        BASE: "/assessment"
        HOST: "${HOST}"
    links:
        - elasticsearch:elasticsearch
        - couchdb:couchdb
        - connect:connect
        - floradata:floradata 
migrator:
    image: cncflora/migrator
    container_name: migrator
    restart: "always"
    ports:
        - "80"
    links:
        - "couchdb:couchdb"
        - "elasticsearch:elasticsearch"
        - "connect:connect"
    environment:
        HOST: "${HOST}"
sig:
    image: cncflora/sig
    container_name: sig
    restart: "always"
    ports:
        - "80"
    links:
        - "couchdb:couchdb"
        - "elasticsearch:elasticsearch"
        - "connect:connect"
    environment:
        HOST: "${HOST}"
reports:
    image: cncflora/reports
    container_name: reports
    restart: "always"
    ports:
        - "80"
        - "9001"
    volumes:
        - "/root/.credentials:/var/www/.credentials"
plataforma2:
    image: cncflora/apache
    container_name: plataforma2
    restart: "always"
    ports:
        - "80"
    volumes:
      - "/var/data/www-old:/var/www:rw"
arquivos:
    image: cncflora/apache
    container_name: arquivos
    restart: "always"
    ports:
        - "80"
    volumes:
        - "/var/data/www:/var/www:rw"
arquivos-sftp:
    image: asavartzeth/sftp
    container_name: arquivos-sftp
    restart: "always"
    ports:
        - "2223:22"
    environment:
        SFTP_USER: "cncflora"
        SFTP_PASS: "1cncflora2"
    volumes:
        - "/var/data/www:$SFTP_DATA_DIR/chroot/www:rw"
wiki:
    image: cncflora/apache
    container_name: wiki 
    restart: "always"
    ports:
        - "80"
    volumes:
        - "/var/data/wiki:/var/www:rw"
wiki-sftp:
    image: asavartzeth/sftp
    container_name: wiki-sftp
    restart: "always"
    ports:
        - "2222:22"
    environment:
        SFTP_USER: "cncflora"
        SFTP_PASS: "1cncflora2"
    volumes:
        - "/var/data/wiki:$SFTP_DATA_DIR/chroot/wiki:rw"
monitis:
    image: cncflora/monitis
    container_name: monitis
    pid: host
    volumes:
        - "/run:/run:ro"
        - "/sys:/sys:ro"
