proxy:
    image: cncflora/proxy
    name: proxy
    restart: "always"
    environment:
        ROOT_APP: "portal"
    ports:
        - "80:80"
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:r"
elasticsearch:
    image: cncflora/elasticsearch
    name: elasticsearch
    restart: "always"
    ports:
        - "9200"
    volumes:
        - "/var/data/elasticsearch/data:/usr/share/elasticsearch/data:rw"
kibana:
    image: cncflora/kibana
    name: kibana
    restart: "always"
    ports:
        - "80"
    links:
        - "elasticsearch:elasticsearch"
download_csv:
    image: cncflora/download_csv
    name: download_csv
    restart: "always"
    ports:
        - "80"
couchdb:
    image: cncflora/couchdb
    name: couchdb
    restart: "always"
    ports:
        - "5984:5984"
        - "9001"
    volumes:
        - "/var/data/couchdb:/var/lib/couchdb:rw"
    links:
        - "elasticsearch:elasticsearch"
services:
    image: cncflora/services
    name: services
    restart: "always"
    ports:
        - "80"
    environment:
        DB: "public"
        PROXY: "/services"
        BASE: "/services"
portal:
    image: cncflora/portal
    name: portal
    restart: "always"
    environment:
        BASE: "/portal"
    ports:
        - 80
entrypoint: 
    image: cncflora/entrypoint
    name: entrypoint
    restart: "always"
    ports:
        - "80"
connect:
    image: cncflora/connect
    name: connect
    restart: "always"
    ports:
        - "80"
    volumes:
        - "/var/data/connect:/var/floraconnect:rw"
    environment:
        PROXY: "/connect"
dwc_services:
    image: cncflora/dwc-services
    name: dwc_services
    restart: "always"
    ports:
        - "80"
    environment:
        PROXY: "/dwc_services"
checklist:
    image: cncflora/checklist
    name: checklist
    restart: "always"
    ports:
        - "80"
    environment:
        BASE: "/checklist"
occurrences:
    image: cncflora/occurrences
    name: occurrences
    restart: "always"
    ports:
        - "80"
    environment:
        BASE: "/occurrences"
profiles:
    image: cncflora/profiles
    name: profiles
    restart: "always"
    ports:
        - "80"
    environment:
        BASE: "/profiles"
assessments:
    image: cncflora/assessments
    name: assessments
    restart: "always"
    ports:
        - "80"
    environment:
        BASE: "/assessment"
migrator:
    image: cncflora/migrator
    name: migrator
    restart: "always"
    ports:
        - "80"
    links:
        - "couchdb:couchdb"
        - "elasticsearch:elasticsearch"
reports:
    image: cncflora/reports
    name: reports
    restart: "always"
    ports:
        - "80"
        - "9001"
floradata:
    image: cncflora/floradata
    name: floradata
    restart: "always"
    environment:
        SERVICE_80_CHECK_HTTP: /api/v1/families
    ports:
        - 80
        - 9001
plataforma2:
    image: cncflora/apache
    name: plataforma2
    restart: "always"
    ports:
        - "80"
    volumes:
      - "/var/data/www-old:/var/www:rw"
arquivos:
    image: cncflora/apache
    name: arquivos
    restart: "always"
    ports:
        - "80"
    volumes:
        - "/var/data/www:/var/www:rw"
arquivos-sftp:
    image: asavartzeth/sftp
    name: arquivos-sftp
    restart: "always"
    ports:
        - "2223:22"
    environment:
        SFTP_USER: "cncflora"
        SFTP_PASS: "1cncflora2"
    volumes:
        - "/var/data/www:$SFTP_DATA_DIR/chroot/www:rw"
wiki:
    image: cncflora/apache
    name: wiki 
    restart: "always"
    ports:
        - "80"
    volumes:
        - "/var/data/wiki:/var/www:rw"
wiki-sftp:
    image: asavartzeth/sftp
    name: wiki-sftp
    restart: "always"
    ports:
        - "2222:22"
    environment:
        SFTP_USER: "cncflora"
        SFTP_PASS: "1cncflora2"
    volumes:
        - "/var/data/wiki:$SFTP_DATA_DIR/chroot/wiki:rw"
monitis:
    image: cncflora/monitis
    name: monitis
    pid: host
    volumes:
        - "/run:/run:ro"
        - "/sys:/sys:ro"
