etcd:
    image: cncflora/etcd
    name: etcd
    restart: "always"
    ports:
       - "4001:4001"
logstash:
    image: diogok/logstash
    name: logstash
    restart: "always"
    ports:
        - 80
        - 9514
        - 9001
portal:
    image: cncflora/portal
    name: portal
    restart: "always"
    environment:
      BASE: "/portal"
    ports:
      - 8000
      - 9001
proxy:
    image: cncflora/proxy 
    name: proxy
    restart: "always"
    environment:
        ROOT_APP: "portal"
    ports:
        - "80:80"
        - "9001"
    links:
        - "etcd:etcd"
elasticsearch:
    image: cncflora/elasticsearch
    name: elasticsearch
    restart: "always"
    ports:
        - "9200"
couchdb:
    image: cncflora/couchdb
    name: couchdb
    restart: "always"
    ports:
        - "5984"
        - "9001"
    volumes:
        - "/var/lib/couchdb:/var/lib/couchdb:rw"
    links:
        - "elasticsearch:elasticsearch"
services:
    image: cncflora/services
    name: services
    restart: "always"
    ports:
        - "8080"
        - "9001"
    environment:
        DB: "public"
        PROXY: "/services"
        BASE: "/services"
entrypoint: 
    image: cncflora/entrypoint
    name: entrypoint
    restart: "always"
    ports:
        - "80"
connect:
    image: cncflora/connect
    name: connect
    restart: "always"
    ports:
        - "8080"
        - "9001"
    volumes:
        - "/var/floraconnect:/var/floraconnect:rw"
    environment:
        PROXY: "/connect"
dwc_services:
    image: cncflora/dwc-services
    name: dwc_services
    restart: "always"
    ports:
        - "8080"
        - "9001"
    environment:
        PROXY: "/dwc_services"
floradata:
    image: cncflora/floradata
    name: floradata
    restart: "always"
    ports:
        - "80"
checklist:
    image: cncflora/checklist
    name: checklist
    restart: "always"
    ports:
        - "8080"
        - "9001"
    environment:
        BASE: "/checklist"
occurrences:
    image: cncflora/occurrences
    name: occurrences
    restart: "always"
    ports:
        - "8080"
        - "9001"
    environment:
        BASE: "/occurrences"
profiles:
    image: cncflora/profiles
    name: profiles
    restart: "always"
    ports:
        - "80"
        - "9001"
    environment:
        BASE: "/profiles"
assessments:
    image: cncflora/assessments
    name: assessments
    restart: "always"
    ports:
        - "8080"
        - "9001"
    environment:
        BASE: "/assessment"
migrator:
    image: cncflora/migrator
    name: migrator
    restart: "always"
    ports:
        - "80"
    links:
        - "couchdb:couchdb"
        - "elasticsearch:elasticsearch"
arquivos:
    image: cncflora/apache
    name: arquivos
    restart: "always"
    ports:
        - "80"
    volumes:
        - "/var/www:/var/www:rw"
wiki:
    image: cncflora/apache
    name: wiki 
    restart: "always"
    ports:
        - "80"
    volumes:
        - "/var/wiki:/var/www:rw"
