etcd:
    image: cncflora/etcd
    name: etcd
    restart: "always"
    ports:
       - "4001:4001"
consul:
    image:  progrium/consul
    name: consul
    restart: "always"
    command: "-server -bootstrap -ui-dir /ui"
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
        -  "8500:8500"
        -  "8600:8600"
registrator:
    image: gliderlabs/registrator:master
    name: registrator
    restart: "always"
    command: "-internal consul://consul:8500"
    ports:
        - 8080
    links: 
        - "consul:consul"
    volumes:
        - "/var/run/docker.sock:/tmp/docker.sock"
alerts:
    image: jess/consul-alerts
    name: alerts
    restart: "always"
    command: "--watch-events --watch-checks --consul-addr=consul:8500 --consul-dc=dc1"
    links:
        - "consul:consul"
resource-monitor:
    image: cncflora/mom
    name: resource-mom
    restart: "always"
    ports:
        - 80
    environment:
        SERVICE_80_CHECK_HTTP: /all.php
logstash:
    image: cncflora/logstash
    name: logstash
    restart: "always"
    ports:
        - 80
        - 9514
        - 9001
logspout:
    image: gliderlabs/logspout
    name: logspout
    restart: "always"
    ports:
        - 8000
    links:
        - "logstash:logstash"
    volumes:
        - "/var/run/docker.sock:/tmp/docker.sock"
    command: "syslog://logstash:9514"
advisor:
    image: google/cadvisor
    name: advisor
    restart: "always"
    ports:
        - 8080
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker:/var/lib/docker:ro"
proxy:
    image: diogok/proxy-docker
    name: proxy
    restart: "always"
    environment:
        ROOT_APP: "portal"
    ports:
        - "80:80"
        - "9001"
    links:
        - "etcd:etcd"
elasticsearch:
    image: cncflora/elasticsearch
    name: elasticsearch
    restart: "always"
    ports:
        - "9200"
    volumes:
      - "/var/elasticsearch/data:/usr/share/elasticsearch/data:rw"
kibana:
    image: cncflora/kibana
    name: kibana
    restart: "always"
    ports:
        - "80"
    links:
        - "elasticsearch:elasticsearch"
couchdb:
    image: cncflora/couchdb
    name: couchdb
    restart: "always"
    ports:
        - "5984:5984"
        - "9001"
    volumes:
        - "/var/lib/couchdb:/var/lib/couchdb:rw"
    links:
        - "elasticsearch:elasticsearch"
services:
    image: cncflora/services
    name: services
    restart: "always"
    ports:
        - "80"
    environment:
        DB: "public"
        PROXY: "/services"
        BASE: "/services"
portal:
    image: cncflora/portal
    name: portal
    restart: "always"
    environment:
        BASE: "/portal"
    ports:
        - 80
entrypoint: 
    image: cncflora/entrypoint
    name: entrypoint
    restart: "always"
    ports:
        - "80"
connect:
    image: cncflora/connect
    name: connect
    restart: "always"
    ports:
        - "80"
    volumes:
        - "/var/floraconnect:/var/floraconnect:rw"
    environment:
        PROXY: "/connect"
dwc_services:
    image: cncflora/dwc-services
    name: dwc_services
    restart: "always"
    ports:
        - "80"
    environment:
        PROXY: "/dwc_services"
checklist:
    image: cncflora/checklist
    name: checklist
    restart: "always"
    ports:
        - "80"
    environment:
        BASE: "/checklist"
occurrences:
    image: cncflora/occurrences
    name: occurrences
    restart: "always"
    ports:
        - "80"
    environment:
        BASE: "/occurrences"
profiles:
    image: cncflora/profiles
    name: profiles
    restart: "always"
    ports:
        - "80"
    environment:
        BASE: "/profiles"
assessments:
    image: cncflora/assessments
    name: assessments
    restart: "always"
    ports:
        - "80"
    environment:
        BASE: "/assessment"
migrator:
    image: cncflora/migrator
    name: migrator
    restart: "always"
    ports:
        - "80"
    links:
        - "couchdb:couchdb"
        - "elasticsearch:elasticsearch"
reports:
    image: cncflora/reports
    name: reports
    restart: "always"
    ports:
        - "80"
        - "9001"
floradata:
    image: cncflora/floradata
    name: floradata
    restart: "always"
    environment:
        SERVICE_80_CHECK_HTTP: /api/v1/families
    ports:
        - 80
        - 9001
plataforma2:
    image: cncflora/apache
    name: plataforma2
    restart: "always"
    ports:
        - "80"
    volumes:
        - "/var/www2:/var/www:rw"
arquivos:
    image: cncflora/apache
    name: arquivos
    restart: "always"
    ports:
        - "80"
    volumes:
        - "/var/www:/var/www:rw"
arquivos-sftp:
    image: asavartzeth/sftp
    name: arquivos-sftp
    restart: "always"
    ports:
        - "2223:22"
    environment:
        SFTP_USER: "cncflora"
        SFTP_PASS: "1cncflora2"
    volumes:
        - "/var/www:$SFTP_DATA_DIR/chroot/www:rw"
wiki:
    image: cncflora/apache
    name: wiki 
    restart: "always"
    ports:
        - "80"
    volumes:
        - "/var/wiki:/var/www:rw"
wiki-sftp:
    image: asavartzeth/sftp
    name: wiki-sftp
    restart: "always"
    ports:
        - "2222:22"
    environment:
        SFTP_USER: "cncflora"
        SFTP_PASS: "1cncflora2"
    volumes:
        - "/var/wiki:$SFTP_DATA_DIR/chroot/wiki:rw"
